version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local